version: "3"

services:
  hust-captcha-resolver:
    image: tuana9a/hust-captcha-resolver
    container_name: hust-captcha-resolver
    build: .
    ports:
      - 8080:8080
    env_file: .env
    restart: unless-stopped
